### PR TITLE
Issue#5 addressed, added favicon

### PR DESCRIPTION
**Pull request by Shresth0903**
Favicon has been added to the website, issue#5 has been addressed

### CODE REVIEW

**Comment by chakri68** [comment]
Can you please add some screenshots as mentioned in [contribution guidelines](https://github.com/iiitl/moviedb/blob/master/CONTRIBUTING.md) showing the visual change - the favicon in this case?

**Comment by Shresth0903** [comment]
The mentioned favicon is now visible

**Comment by chakri68** [comment]
Cool, we can edit our messages on github. So, try to edit your first message so that other people can see what you've done👍

- Issue subject should be ideally of format `#[Issue No.] Subject`. So, in this case it can be `#5 Added favicon`

Thanks for contributing! ✨

**Comment by Shresth0903** [comment]
> Cool, we can edit our messages on github. So, try to edit your first message so that other people can see what you've done👍
> 
> * Issue subject should be ideally of format `#[Issue No.] Subject`. So, in this case it can be `#5 Added favicon`
> 
> Thanks for contributing! ✨

Thank you for the assistance

**Pull request closed without merging**
