### PR TITLE
#8 Now the webpage is not scrolling when the movie dialog box is opened

### PR DESCRIPTION
**Pull request by umeshSinghVerma**
fixes #8 
Screenshot from 2023-02-06 20-17-39
See here that there is no scroll bar there

### CODE REVIEW

**Comment by chakri68** [comment]
Works well, but try to use things that are already present in the codebase like styles in CSS.

As I mentioned before, please create a new branch for new issues.

**Comment by umeshSinghVerma** [comment]
Sir I am creating a new branch for every issue still it show into the same
I write
Git checkout -b issue6
Then  I am working into that one
Sir can you please guide me what is the correct way of making the new
branch please sir

**Comment by chakri68** [comment]
Send me your WhatsApp no./discord id through [mail](mailto:lci2021011@iiitl.ac.in)

**Comment by umeshSinghVerma** [comment]
9719656928
Sir this is my number

**Pull request closed without merging**
