### PR TITLE
Solved #4 : Added suitable footer, matching theme of website

### PR DESCRIPTION
**Pull request by destroycompiler**
solved #4 
---
## Additions

- Footer exactly matches the theme of website
- Footer contains the following 
1. Movie DB icon
2. Title
3. Copyright Symbol
---
> Extra Contribution to footer
- Social Media Links for Twitter Instagram and Facebook

- The footer doesn't interfere with other elements of the website.  
---

## Screenshot of the Solved Issue

Screenshot_20230206_123933

### CODE REVIEW

**Comment by destroycompiler** [comment]
- also the links have hover animation added to them.

**Comment by chakri68** [comment]
The footer looks great!

My only pet peeve would be that the class `title` already exists in `global.css`. So, any new styles added to `.title` in the footer section override the styles declared before them. 

<p align="center">
image
</p>

So, try to create new classes or create css declarations using a more specific selector like `footer .title`

Also, you can make the body have `min-height` of `100vh` to ensure that the footer always stays at the bottom of the webpage.

Great PR tho. 

Thanks for contributing! ✨

**Comment by destroycompiler** [comment]
Sure, sir, I will fix them in the next commit

**Comment by destroycompiler** [comment]
Sir, I have fixed the bugs regarding the footer, and I have committed to the branch, but the PR has been closed, so should I request a new PR incorporating the changes?

**Comment by chakri68** [comment]
Looks good now ✨

**Pull request closed without merging**
